version: '3'

services:
  web:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: app_nginx
    #    environment:
    #      - NGINX_HOST=foobar.com
    #      - NGINX_PORT=80

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    user: 1000:1000
    depends_on:
      - db
    container_name: app

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: game_quiz
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8101:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: game_quiz_db

